language: node_js
node_js:
  - 10
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
if: tag IS blank
jobs:
  include:
    - stage: release
      before_script: npm run build
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
